function [block_pos_x,block_pos_y] = getBlockPos(obs_pose,obs_size)
%GETBLOCKPOS Summary of this function goes here
%   Detailed explanation goes here
        block_pos_x = [obs_pose(1)-obs_size(1)/2; ...
            obs_pose(1)+obs_size(1)/2; ...
            obs_pose(1)+obs_size(1)/2; ...
            obs_pose(1)-obs_size(1)/2];

        block_pos_y = [obs_pose(2)-obs_size(2)/2; ...
            obs_pose(2)-obs_size(2)/2; ...
            obs_pose(2)+obs_size(2)/2; ...
            obs_pose(2)+obs_size(2)/2];
end

